import { SlideData, ExhibitItem } from './types';

export const SCENES_DATA: SlideData[] = [
  {
    id: 0,
    title: "迎风聚智",
    subtitle: "数智启航 · 自主可控",
    englishTitle: "WIND GATHER INTELLIGENCE",
    tagline: "军民融合 / 国内首创 / 基础软件检验检测先锋",
    description: "武汉迎风聚智科技有限公司创立于2013年，深耕计算机软硬件检验检测核心技术。",
    accentColor: "#c20a0a",
    themeColor: "from-red-950 via-neutral-950 to-neutral-950"
  },
  {
    id: 1,
    title: "测试用例自动生成",
    subtitle: "AI驱动 · 零代码覆盖",
    englishTitle: "AUTO TEST GENERATION",
    tagline: "智能化测试用例设计与生成平台",
    description: "基于AI大模型的测试用例自动生成工具，从需求到用例全链路智能化。",
    accentColor: "#7c3aed",
    themeColor: "from-violet-950 via-neutral-950 to-neutral-950"
  },
  {
    id: 2,
    title: "WebRunner & GUIRunner",
    subtitle: "性能测试 · 功能验证",
    englishTitle: "PERFORMANCE & FUNCTIONAL TESTING",
    tagline: "系统与软件性能测试 + 功能测试全覆盖",
    description: "WebRunner性能压测引擎与GUIRunner功能自动化测试工具，国产替代LoadRunner。",
    accentColor: "#e61919",
    themeColor: "from-neutral-900 via-zinc-950 to-neutral-950"
  },
  {
    id: 3,
    title: "数据库基准测试",
    subtitle: "TPC-E · TPC-DS 标准跑分",
    englishTitle: "DATABASE BENCHMARK",
    tagline: "国内唯一自主数据库基准测试工具制造商",
    description: "标准化TPC-E/TPC-DS基准测试，适配国产数据库生态，一键跑分出报告。",
    accentColor: "#0891b2",
    themeColor: "from-cyan-950 via-neutral-950 to-neutral-950"
  },
  {
    id: 4,
    title: "军用数据集管理平台",
    subtitle: "多密级 · 安全管控",
    englishTitle: "MILITARY DATA MANAGEMENT",
    tagline: "面向军工领域的高安全数据集管理系统",
    description: "支持多密级数据分类管理、权限管控与安全审计，满足军工数据治理需求。",
    accentColor: "#065f46",
    themeColor: "from-emerald-950 via-neutral-950 to-neutral-950"
  },
  {
    id: 5,
    title: "轻量化数据库备份",
    subtitle: "增量备份 · 秒级恢复",
    englishTitle: "LIGHTWEIGHT DB BACKUP",
    tagline: "低资源占用的数据库备份与恢复工具",
    description: "轻量化设计，支持增量备份与秒级恢复，跨平台适配国产数据库。",
    accentColor: "#b45309",
    themeColor: "from-amber-950 via-neutral-950 to-neutral-950"
  },
  {
    id: 6,
    title: "AgentRunner 智体平台",
    subtitle: "AI智体 · 自动化测试",
    englishTitle: "AI AGENT RUNNER",
    tagline: "大模型驱动的智能测试自动化平台",
    description: "以AI Agent为核心，实现测试用例录制、脚本生成、执行与GJB文档自动输出。",
    accentColor: "#06b6d4",
    themeColor: "from-slate-950 via-zinc-950 to-neutral-950"
  },
  {
    id: 7,
    title: "合作伙伴",
    subtitle: "军民企业 · 生态共建",
    englishTitle: "PARTNERS & ECOSYSTEM",
    tagline: "覆盖军工科研、检测认证、头部企业全生态",
    description: "与30+军工科研院所、国家级检测机构及头部ICT企业建立深度合作。",
    accentColor: "#1d4ed8",
    themeColor: "from-blue-950 via-neutral-950 to-neutral-950"
  }
];

export const EXHIBIT_LIST: ExhibitItem[] = [
  {
    id: 'intro',
    name: '迎风聚智',
    subtitle: '基础软件检验检测技术研发先锋',
    englishTag: 'LEMING TECH',
    accentColor: '#c20a0a',
    themeColor: 'from-red-950 via-neutral-950 to-neutral-950',
    keywords: [
      { icon: 'Building2', label: '成立于2013', sublabel: '武汉 · 十年深耕', statValue: '2013' },
      { icon: 'FileCheck', label: '专利27项', sublabel: '50+软著', statValue: '27+' },
      { icon: 'Target', label: '37+重大项目', sublabel: '国家级课题', statValue: '37+' },
      { icon: 'Shield', label: 'GJB认证', sublabel: '军工级资质', statValue: 'GJB' },
    ],
    coreCapabilities: [
      { icon: 'ClipboardCheck', label: '测试管理平台' },
      { icon: 'Microscope', label: '基准测试工具' },
      { icon: 'Server', label: '系统与软件测试' },
      { icon: 'Cloud', label: '云网端质量保障' },
      { icon: 'Database', label: '数据质量管理' },
      { icon: 'BrainCircuit', label: '大模型测试工具' },
    ],
    certifications: ['CMA', 'CNAS', 'GJB 9001C', 'ISO27001', 'CMMI3', '军工保密'],
  },
  {
    id: 'auto-testgen',
    name: '测试用例自动生成工具',
    subtitle: '从需求到用例，AI全链路智能生成',
    englishTag: 'AUTO TEST GENERATION',
    accentColor: '#7c3aed',
    themeColor: 'from-violet-950 via-neutral-950 to-neutral-950',
    keywords: [
      { icon: 'Sparkles', label: 'AI驱动', sublabel: '大模型智能解析' },
      { icon: 'Code2', label: '零代码', sublabel: '无需编程基础' },
      { icon: 'ListChecks', label: '需求全覆盖', sublabel: '自动追溯矩阵' },
      { icon: 'FileCheck', label: 'GJB合规', sublabel: '军标文档输出' },
    ],
    videoUrl: '/videos/webrunner.mp4',
    videoLabel: '一分钟看懂 测试用例自动生成',
    screenshots: ['/screenshots/auto-testgen-1.png', '/screenshots/auto-testgen-2.png', '/screenshots/auto-testgen-3.png'],
  },
  {
    id: 'webrunner-guirunner',
    name: 'WebRunner & GUIRunner',
    subtitle: '系统性能压测 + 功能自动化验证',
    englishTag: 'PERFORMANCE & FUNCTIONAL',
    accentColor: '#e61919',
    themeColor: 'from-neutral-900 via-zinc-950 to-neutral-950',
    keywords: [
      { icon: 'Zap', label: '超高并发', sublabel: '万级vUser压测' },
      { icon: 'Timer', label: '微秒响应', sublabel: 'P99延迟分析' },
      { icon: 'Replace', label: '国产替代', sublabel: '替换LoadRunner' },
      { icon: 'Monitor', label: '全界面覆盖', sublabel: 'GUI自动录制回放' },
    ],
    videoUrl: '/videos/webrunner.mp4',
    videoLabel: '一分钟看懂 WebRunner',
    screenshots: ['/screenshots/webrunner-1.png', '/screenshots/webrunner-2.png', '/screenshots/webrunner-3.png'],
  },
  {
    id: 'db-benchmark',
    name: '数据库基准测试 TPC-E/TPC-DS',
    subtitle: '国内唯一自主基准测试工具制造商',
    englishTag: 'DATABASE BENCHMARK',
    accentColor: '#0891b2',
    themeColor: 'from-cyan-950 via-neutral-950 to-neutral-950',
    keywords: [
      { icon: 'BarChart3', label: '标准化跑分', sublabel: 'TPC国际规范' },
      { icon: 'Database', label: '多库适配', sublabel: '达梦/OceanBase/GaussDB' },
      { icon: 'Play', label: '一键部署', sublabel: '自动化测试流程' },
      { icon: 'Award', label: '权威认证', sublabel: '国家标准制定者' },
    ],
    videoUrl: '/videos/webrunner.mp4',
    videoLabel: '一分钟看懂 数据库基准测试',
    screenshots: ['/screenshots/db-benchmark-1.png', '/screenshots/db-benchmark-2.png', '/screenshots/db-benchmark-3.png'],
  },
  {
    id: 'military-data',
    name: '军用数据集管理平台',
    subtitle: '面向军工领域的高安全数据集管理系统',
    englishTag: 'MILITARY DATA PLATFORM',
    accentColor: '#065f46',
    themeColor: 'from-emerald-950 via-neutral-950 to-neutral-950',
    keywords: [
      { icon: 'ShieldCheck', label: '军工级安全', sublabel: '等保三级+' },
      { icon: 'Layers', label: '数据治理', sublabel: '全生命周期管理' },
      { icon: 'Lock', label: '多密级管控', sublabel: '分级权限体系' },
      { icon: 'Cpu', label: '自主可控', sublabel: '国产芯片适配' },
    ],
    videoUrl: '/videos/webrunner.mp4',
    videoLabel: '一分钟看懂 军用数据集管理',
    screenshots: ['/screenshots/military-data-1.png', '/screenshots/military-data-2.png', '/screenshots/military-data-3.png'],
  },
  {
    id: 'db-backup',
    name: '轻量化数据库备份工具',
    subtitle: '低资源占用，增量备份与秒级恢复',
    englishTag: 'LIGHTWEIGHT BACKUP',
    accentColor: '#b45309',
    themeColor: 'from-amber-950 via-neutral-950 to-neutral-950',
    keywords: [
      { icon: 'HardDriveDownload', label: '增量备份', sublabel: '差异化存储' },
      { icon: 'RotateCcw', label: '秒级恢复', sublabel: '快速回滚' },
      { icon: 'Gauge', label: '低资源占用', sublabel: '轻量化设计' },
      { icon: 'Laptop', label: '跨平台', sublabel: '信创全适配' },
    ],
    videoUrl: '/videos/webrunner.mp4',
    videoLabel: '一分钟看懂 数据库备份',
    screenshots: ['/screenshots/db-backup-1.png', '/screenshots/db-backup-2.png', '/screenshots/db-backup-3.png'],
  },
  {
    id: 'agentrunner',
    name: 'AgentRunner 智体平台',
    subtitle: '大模型驱动的智能测试自动化平台',
    englishTag: 'AI AGENT RUNNER',
    accentColor: '#06b6d4',
    themeColor: 'from-slate-950 via-zinc-950 to-neutral-950',
    keywords: [
      { icon: 'Bot', label: 'AI智体', sublabel: '多Agent协同' },
      { icon: 'TestTube2', label: '自动化测试', sublabel: '全流程无人值守' },
      { icon: 'FileText', label: '文档生成', sublabel: 'GJB438C合规' },
      { icon: 'Eye', label: '多模态', sublabel: '视觉+语义理解' },
    ],
    videoUrl: '/videos/webrunner.mp4',
    videoLabel: '一分钟看懂 AgentRunner',
    screenshots: ['/screenshots/agentrunner-1.png', '/screenshots/agentrunner-2.png', '/screenshots/agentrunner-3.png'],
  },
  {
    id: 'partners',
    name: '合作伙伴',
    subtitle: '覆盖军工科研、检测认证、头部企业全生态',
    englishTag: 'PARTNERS & ECOSYSTEM',
    accentColor: '#1d4ed8',
    themeColor: 'from-blue-950 via-neutral-950 to-neutral-950',
    keywords: [
      { icon: 'Shield', label: '军工科研', sublabel: '8+研究所' },
      { icon: 'BadgeCheck', label: '检测机构', sublabel: '13+机构' },
      { icon: 'Building2', label: '企业合作', sublabel: '14+企业' },
      { icon: 'Target', label: '生态覆盖', sublabel: '35+合作方' },
    ],
  }
];
